### ISSUE TITLE
Higher supported sample rates?

### ISSUE THREAD

**Issue by Vaporeon** [duncanthrax/scream#14]
Would it be possible to support higher sample rates, like 48000 or 96000kHz?

**Comment by duncanthrax** [comment]
A higher static sample rate is trivial, if you want to build yourself, just look for
``
#define MIN_SAMPLE_RATE             44100   // Min Sample Rate
#define MAX_SAMPLE_RATE             44100   // Max Sample Rate
``
in scream.h. The Windows audio subsystem will resample as required. You might also want to modify CHUNK_SIZE in savedata.cpp so that an even number of samples fits in exactly one packet. Dynamic sample rates aren't possible with the current "protocol" (in quotes, because there isn't any :) ).
 
Making the static rate configurable might be possible, I'll check that out next time I do a build.

**Comment by Teteros** [comment]
I'd like to add to the above that the receivers also need to be modified andrebuild or you will get sped up or slowed down playback on Linux if there's a sample rate mismatch between the receiver/scream.

[Alsa](https://github.com/duncanthrax/scream/blob/master/Receivers/alsa/scream-alsa.c#L141) / [Pulse](https://github.com/duncanthrax/scream/blob/master/Receivers/pulseaudio/scream-pulse.c) lines to change.

**Comment by duncanthrax** [comment]
It took a while, but this has now been added. See the front page.
