### ISSUE TITLE
Multichannel above Stereo not working on Windows 10

### ISSUE THREAD

**Issue by ujLion** [duncanthrax/scream#56]
Mono and Stereo works, but when I change to Multichannel configuration - there is no sound.
Data is received on the receiving computer though. Using latest release v3.3

If there is a channel mapping issue, how about having a mapping config file that user can edit to establish correct mapping.

**Comment by ujLion** [comment]
Using 'ScreamReader' receiver

**Comment by martinellimarco** [comment]
Hi @ujLion 
the ScreamReader .net receiver is the less tested for multichannel support. Honestly I patched it 6 months ago and never looked at it again.
I've looked at the code but I can't spot any obvious bug, give me a few hours and I'll test it properly.
About the channel map, the assumption I made was that both the sender and the receiver had to be set with the same multichannel settings.
For example, if your scream receiver is set to surround 5.1 with front, right, center, rear-left, rear-right and LFE the same channel map has to be set on your transmitter.
If not you should still ear the sound but on the wrong channel.
Can you check if both your transmitter and receiver share the same settings?

**Comment by ujLion** [comment]
Hi @martinellimarco 
Sure take your time. And yes, both transmitter and receiver share the same settings. viz 5.1 with same sample rate.
I tried other permutations as well, but to no avail - no audio at all

// { irrelevant to this bug }
Using it to stream 5.1 audio from laptop to old desktop - since laptop and monitor over HDMI only have stereo. For now have soldered front and rear to a single to jack (2 female one male).

**Comment by martinellimarco** [comment]
Hi @ujLion 
I've took the time to look into this problem.
I've found out that it was working for me only because I had an obscure configuration on my windows machine, but in general it wasn't working.
I've changed audio backend, from WaveOut to WASAPI and I can see it's able to open the output device for multichannel now.
The thing is, both with the old WaveOut and with the new WASAPI I can't really hear if it is sounding right or not. My only windows machine, besides the one running scream, is an ancient laptop with wifi b/g and it sounds terrible even in mono.
Can you test [this release](https://send.firefox.com/download/3ae241e2772cc0a1/#oAVhxnhBqqg9_tEYtZS0UQ) and tell me if it sounds ok?  If so I'll push the update

**Comment by ujLion** [comment]
@martinellimarco Thanks a lot! It's working flawless now 👍🙂

**Comment by martinellimarco** [comment]
@duncanthrax When you have the time can you release this?

**Comment by duncanthrax** [comment]
Released as 3.4: https://github.com/duncanthrax/scream/releases/tag/3.4

Thanks for taking care during holiday season :)
